# Conda environment for Azure AI Foundry deployment
name: foundry-agent-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=23.0
  - pip:
      - azure-ai-inference>=1.0.0
      - azure-identity>=1.15.0
      - openai>=1.12.0
      - azure-core>=1.29.0
      - pyyaml>=6.0
      - requests>=2.31.0
      - flask>=3.0.0
      - inference-schema>=1.5.0
